<a href="https://colab.research.google.com/github/ArjunMal1311/ML/blob/main/Tensorflow/1-Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# We have several neural network lanes or stacks also known as mathematical functions

# 2 parameters are considered -> weight and bias
# In a neural network, weights are the learnable parameters that determine the strength of connections between neurons in different layers. Each connection between two neurons has an associated weight.
# Biases are another set of learnable parameters in a neural network. They are added to the weighted sum of neuron inputs to introduce flexibility and shift the activation function.


# Imagine you have a recipe, and the ingredients have different weights. Some ingredients, like salt, may need a smaller amount (weight) to make the dish taste good, while others, like sugar, may need a larger amount (weight).
# Picture a see-saw. The bias is like the position at which the see-saw starts. If it starts tilted to one side (positive bias), it will naturally lean in that direction, and if it starts level (zero bias), it will stay balanced.

# Layer 1 -> Layer2 -> Layer3 ...... -> Layer n
# So x1 be the input to layer1 produces y1 which will be input to layer2
# Our aim is to obtain the value of w and b     wX + b = Y

# To train we use inputs and outputs, multi dimensional arrays are known as tensors


In [ ]:
# [8] 0-D Tensor, Single element
# [2 0 -3] 1-D  Tensor which consist of multiple 0-D Tensors

# [1 2  0] # 2-D Array consisting of multiple 1D Tensors
# [3 5 -1]
# [3 4  5]

# 3-D Tensor consist of multiple 2-D Arrays [1-3DTensor.jpg]

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [3]:
ten_one_d = tf.constant([2, 0, -3]) # We can also have float, even one float then dtype changes to float
ten_one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  0, -3], dtype=int32)>

In [5]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
tensor_two_d

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  0],
       [ 3,  5, -1],
       [ 1,  5,  6],
       [ 2,  3,  8]], dtype=int32)>

In [6]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
     [3, 5, -1]],

    [[10, 2, 0],
     [1, 0, 2]],

    [[2, 1, 9],
     [4, -2, 32]],

])

tensor_three_d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 2,  1,  9],
        [ 4, -2, 32]]], dtype=int32)>