<a href="https://colab.research.google.com/github/ArjunMal1311/ML/blob/main/Tensorflow/1-Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# We have several neural network lanes or stacks also known as mathematical functions

# 2 parameters are considered -> weight and bias
# In a neural network, weights are the learnable parameters that determine the strength of connections between neurons in different layers. Each connection between two neurons has an associated weight.
# Biases are another set of learnable parameters in a neural network. They are added to the weighted sum of neuron inputs to introduce flexibility and shift the activation function.


# Imagine you have a recipe, and the ingredients have different weights. Some ingredients, like salt, may need a smaller amount (weight) to make the dish taste good, while others, like sugar, may need a larger amount (weight).
# Picture a see-saw. The bias is like the position at which the see-saw starts. If it starts tilted to one side (positive bias), it will naturally lean in that direction, and if it starts level (zero bias), it will stay balanced.

# Layer 1 -> Layer2 -> Layer3 ...... -> Layer n
# So x1 be the input to layer1 produces y1 which will be input to layer2
# Our aim is to obtain the value of w and b     wX + b = Y

# To train we use inputs and outputs, multi dimensional arrays are known as tensors


In [ ]:
# [8] 0-D Tensor, Single element
# [2 0 -3] 1-D  Tensor which consist of multiple 0-D Tensors

# [1 2  0] # 2-D Array consisting of multiple 1D Tensors
# [3 5 -1]
# [3 4  5]

# 3-D Tensor consist of multiple 2-D Arrays [1-3DTensor.jpg]

In [2]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
ten_one_d = tf.constant([2, 0, -3]) # We can also have float, even one float then dtype changes to float
ten_one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  0, -3], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
tensor_two_d

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  0],
       [ 3,  5, -1],
       [ 1,  5,  6],
       [ 2,  3,  8]], dtype=int32)>

In [ ]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
     [3, 5, -1]],

    [[10, 2, 0],
     [1, 0, 2]],

    [[2, 1, 9],
     [4, -2, 32]],

])

tensor_three_d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 2,  1,  9],
        [ 4, -2, 32]]], dtype=int32)>

In [9]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns = 3,
    batch_shape = [2, ],
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor)
eye_tensor.shape

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]]], shape=(2, 4, 3), dtype=float32)


TensorShape([2, 4, 3])

In [10]:
ones_tensor = tf.ones(
    [5, 3, 2],
    dtype = tf.dtypes.float32,
    name = None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [13]:
# Now we have one_like
# Creates the tensor of all ones
# like we have 2*3 matrix
# [12 1 3]
# [5 7 2]

# Now when we input this into one_like we will obtain
# [1 1 1]
# [1 1 1]  one_like takes in shape and output all 1's in that shape

# similar to ones we have zeros
zeros_tensor = tf.zeros(
    [3, 2],
    dtype= tf.dtypes.int32,
    name = None
)
zeros_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [14]:
# Rank ->
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[
                      [1, 1, 1],
                       [2, 2, 2]
                  ]
                 ,
                  [
                      [3, 3, 3],
                       [4, 4, 4]
                  ]
                 ])
tf.rank(t)  # 3 dimensional

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [15]:
tf.size(t) # Number of elements in the tensor

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [18]:
# Random normal tensor

random_tensor = tf.random.normal( # Random Distribution
    [3, 2],
    mean = 100.0,
    stddev = 1.0,
    name = None
)

random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[101.044464, 100.942   ],
       [100.64783 , 101.08344 ],
       [100.29241 , 100.30865 ]], dtype=float32)>

In [24]:
random_tensor = tf.random.uniform( # Uniform distribution
    [3, 2],
    minval = 0,
    maxval = 50,
    dtype = tf.dtypes.int32,
    name = None
)

random_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[22, 24],
       [30, 36],
       [21, 48]], dtype=int32)>

In [26]:
import numpy as np
# Set a seed for TensorFlow
tf.random.set_seed(42)

# Generate random numbers using TensorFlow
rand_nums = tf.random.uniform(shape=(3, 3))
print(rand_nums.numpy())  # This will produce the same random numbers every time

# Set a seed for NumPy
np.random.seed(42)

# Generate random numbers using NumPy
rand_nums_np = np.random.uniform(size=(3, 3))
print(rand_nums_np)  # This will produce the same random numbers every time

[[0.6645621  0.44100678 0.3528825 ]
 [0.46448255 0.03366041 0.68467236]
 [0.74011743 0.8724445  0.22632635]]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [51]:
tf.random.set_seed(4)

random_tensor = tf.random.uniform( # Uniform distribution
    [3, 2],
    minval = 0,
    maxval = 50,
    dtype = tf.dtypes.int32,
    name = None,
    seed = 2
)

# This is the seed for the random number generator. Setting a seed ensures that the random values generated are reproducible. If you run this code multiple times with the same seed (seed=20), you will get the same random tensor each time.

random_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[31, 18],
       [22, 48],
       [36, 24]], dtype=int32)>

In [55]:
tensor_indexed= tf.constant([10, 20, 30, 40, 50, 60])
print(tensor_indexed[1:4])
print(tensor_indexed[3:-1])
print(tensor_indexed[3:-2])

tf.Tensor([20 30 40], shape=(3,), dtype=int32)
tf.Tensor([40 50], shape=(2,), dtype=int32)
tf.Tensor([40], shape=(1,), dtype=int32)


In [63]:
tensor_two_d = tf.constant([[1, 2, 0],
                           [3, 5, -1],
                           [1, 5, 6],
                           [2, 3, 8]])

print(tensor_two_d[0:3, 0:2])
print("")
print(tensor_two_d[0:3, :])
print("")
print(tensor_two_d[:, :2])
print("")
print(tensor_two_d[:, 1])
print("")
print(tensor_two_d[..., 1]) # Pick up everything


tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]
 [2 3]], shape=(4, 2), dtype=int32)

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [70]:
tensor_three_d = tf.constant([

                              [[1, 2, 0],
                               [3, 5, -1]],

                              [[10, 2, 0],
                               [1, 0, 2]],

                              [[5, 8, 0],
                               [2, 7, 0]],

                              [[2, 1, 9],
                               [4, -3, 32]]])

print(tensor_three_d[0, :, :])
print("")
print("LINE")
print("")
print(tensor_three_d[0:2, :, 2])
print("")
print("----------")
print("")
print(tensor_three_d[0, ..., :])
print("")
print("----------")
print("")
print(tensor_three_d[..., :, :])
print("")
print("----------")
print("")
print(tensor_three_d[2:4, 1:2, 2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)

LINE

tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)

----------

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)

----------

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)

----------

tf.Tensor(
[[ 0]
 [32]], shape=(2, 1), dtype=int32)

----------

