<a href="https://colab.research.google.com/github/ArjunMal1311/ML/blob/main/Tensorflow/1-Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# We have several neural network lanes or stacks also known as mathematical functions

# 2 parameters are considered -> weight and bias
# In a neural network, weights are the learnable parameters that determine the strength of connections between neurons in different layers. Each connection between two neurons has an associated weight.
# Biases are another set of learnable parameters in a neural network. They are added to the weighted sum of neuron inputs to introduce flexibility and shift the activation function.


# Imagine you have a recipe, and the ingredients have different weights. Some ingredients, like salt, may need a smaller amount (weight) to make the dish taste good, while others, like sugar, may need a larger amount (weight).
# Picture a see-saw. The bias is like the position at which the see-saw starts. If it starts tilted to one side (positive bias), it will naturally lean in that direction, and if it starts level (zero bias), it will stay balanced.

# Layer 1 -> Layer2 -> Layer3 ...... -> Layer n
# So x1 be the input to layer1 produces y1 which will be input to layer2
# Our aim is to obtain the value of w and b     wX + b = Y

# To train we use inputs and outputs, multi dimensional arrays are known as tensors


In [ ]:
# [8] 0-D Tensor, Single element
# [2 0 -3] 1-D  Tensor which consist of multiple 0-D Tensors

# [1 2  0] # 2-D Array consisting of multiple 1D Tensors
# [3 5 -1]
# [3 4  5]

# 3-D Tensor consist of multiple 2-D Arrays [1-3DTensor.jpg]

In [2]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
ten_one_d = tf.constant([2, 0, -3]) # We can also have float, even one float then dtype changes to float
ten_one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  0, -3], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
tensor_two_d

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  0],
       [ 3,  5, -1],
       [ 1,  5,  6],
       [ 2,  3,  8]], dtype=int32)>

In [ ]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
     [3, 5, -1]],

    [[10, 2, 0],
     [1, 0, 2]],

    [[2, 1, 9],
     [4, -2, 32]],

])

tensor_three_d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 2,  1,  9],
        [ 4, -2, 32]]], dtype=int32)>

In [ ]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns = 3,
    batch_shape = [2, ],
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor)
eye_tensor.shape

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]]], shape=(2, 4, 3), dtype=float32)


TensorShape([2, 4, 3])

In [ ]:
ones_tensor = tf.ones(
    [5, 3, 2],
    dtype = tf.dtypes.float32,
    name = None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [ ]:
# Now we have one_like
# Creates the tensor of all ones
# like we have 2*3 matrix
# [12 1 3]
# [5 7 2]

# Now when we input this into one_like we will obtain
# [1 1 1]
# [1 1 1]  one_like takes in shape and output all 1's in that shape

# similar to ones we have zeros
zeros_tensor = tf.zeros(
    [3, 2],
    dtype= tf.dtypes.int32,
    name = None
)
zeros_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [ ]:
# Rank ->
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[
                      [1, 1, 1],
                       [2, 2, 2]
                  ]
                 ,
                  [
                      [3, 3, 3],
                       [4, 4, 4]
                  ]
                 ])
tf.rank(t)  # 3 dimensional

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tf.size(t) # Number of elements in the tensor

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
# Random normal tensor

random_tensor = tf.random.normal( # Random Distribution
    [3, 2],
    mean = 100.0,
    stddev = 1.0,
    name = None
)

random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[101.044464, 100.942   ],
       [100.64783 , 101.08344 ],
       [100.29241 , 100.30865 ]], dtype=float32)>

In [ ]:
random_tensor = tf.random.uniform( # Uniform distribution
    [3, 2],
    minval = 0,
    maxval = 50,
    dtype = tf.dtypes.int32,
    name = None
)

random_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[22, 24],
       [30, 36],
       [21, 48]], dtype=int32)>

In [ ]:
import numpy as np
# Set a seed for TensorFlow
tf.random.set_seed(42)

# Generate random numbers using TensorFlow
rand_nums = tf.random.uniform(shape=(3, 3))
print(rand_nums.numpy())  # This will produce the same random numbers every time

# Set a seed for NumPy
np.random.seed(42)

# Generate random numbers using NumPy
rand_nums_np = np.random.uniform(size=(3, 3))
print(rand_nums_np)  # This will produce the same random numbers every time

[[0.6645621  0.44100678 0.3528825 ]
 [0.46448255 0.03366041 0.68467236]
 [0.74011743 0.8724445  0.22632635]]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [ ]:
tf.random.set_seed(4)

random_tensor = tf.random.uniform( # Uniform distribution
    [3, 2],
    minval = 0,
    maxval = 50,
    dtype = tf.dtypes.int32,
    name = None,
    seed = 2
)

# This is the seed for the random number generator. Setting a seed ensures that the random values generated are reproducible. If you run this code multiple times with the same seed (seed=20), you will get the same random tensor each time.

random_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[31, 18],
       [22, 48],
       [36, 24]], dtype=int32)>

In [ ]:
tensor_indexed= tf.constant([10, 20, 30, 40, 50, 60])
print(tensor_indexed[1:4])
print(tensor_indexed[3:-1])
print(tensor_indexed[3:-2])

tf.Tensor([20 30 40], shape=(3,), dtype=int32)
tf.Tensor([40 50], shape=(2,), dtype=int32)
tf.Tensor([40], shape=(1,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1, 2, 0],
                           [3, 5, -1],
                           [1, 5, 6],
                           [2, 3, 8]])

print(tensor_two_d[0:3, 0:2])
print("")
print(tensor_two_d[0:3, :])
print("")
print(tensor_two_d[:, :2])
print("")
print(tensor_two_d[:, 1])
print("")
print(tensor_two_d[..., 1]) # Pick up everything


tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]
 [2 3]], shape=(4, 2), dtype=int32)

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([

                              [[1, 2, 0],
                               [3, 5, -1]],

                              [[10, 2, 0],
                               [1, 0, 2]],

                              [[5, 8, 0],
                               [2, 7, 0]],

                              [[2, 1, 9],
                               [4, -3, 32]]])

print(tensor_three_d[0, :, :])
print("")
print("LINE")
print("")
print(tensor_three_d[0:2, :, 2])
print("")
print("----------")
print("")
print(tensor_three_d[0, ..., :])
print("")
print("----------")
print("")
print(tensor_three_d[..., :, :])
print("")
print("----------")
print("")
print(tensor_three_d[2:4, 1:2, 2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)

LINE

tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)

----------

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)

----------

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)

----------

tf.Tensor(
[[ 0]
 [32]], shape=(2, 1), dtype=int32)

----------



In [ ]:
# We have various mathematical functions
# like

x_abs = tf.constant([-2, 4])
tf.abs(x_abs)

x_complx = tf.constant([-2 + 5j, 4 - 4j])
tf.abs(x_complx)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([5.38516481, 5.65685425])>

In [ ]:
x_1 = tf.constant([5, 3, 6, 6, 4, 6], dtype=tf.float32)
x_2 = tf.constant([4, 3, 2, 1, 6, 2], dtype=tf.float32)

# tf.divide(x_1, x_2)

# what if x_2 contains a zero?
tf.math.divide_no_nan(x_1, x_2)


# We have similar methods for add, subtract
tf.math.add(x_1, x_2)

tf.math.multiply(x_1, x_2)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([20.,  9., 12.,  6., 24., 12.], dtype=float32)>

In [ ]:
x_1 = tf.constant([5, 3, 6, 6, 4, 6], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)

# ** This is not matrix multiplication **

# x_1 will get change to 6x3
# 5 3 6 6 4 6
# 5 3 6 6 4 6
# 5 3 6 6 4 6

# and x_2 to  3x3
# 7 7 7 7 7 7
# 5 5 5 5 5 5
# 3 3 3 3 3 3

tf.math.multiply(x_1, x_2)


(6,)
(3, 1)


<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[35., 21., 42., 42., 28., 42.],
       [25., 15., 30., 30., 20., 30.],
       [15.,  9., 18., 18., 12., 18.]], dtype=float32)>

In [ ]:
tf.math.minimum(x_1, x_2)

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[5., 3., 6., 6., 4., 6.],
       [5., 3., 5., 5., 4., 5.],
       [3., 3., 3., 3., 3., 3.]], dtype=float32)>

In [ ]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x_argmax))

# we get the index or position of the max value
y_argmax = tf.constant([2, 3, 4, 7, 5, 6])
print(tf.math.argmax(y_argmax))

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [ ]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])

print(x_argmax.shape)

print(tf.math.argmax(x_argmax, 0)) # we specify axis 0 so it compares 2 3 14 and rest all columns




print(tf.math.argmax(x_argmax, 1)) # we specify axis 1 so it compares 2 20 30 3 6 and rest all rows

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant([2, 4])
y = tf.constant(2)

tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tensor_two_d = tf.constant([[1, 2, 0],
                           [3, 5, -1],
                           [1, 5, 6],
                           [2, 3, 8]])

tf.math.reduce_sum(    # 1+ 2+ 0 + 3+ 5+ (-1) ..... + 2+ 3+ 8
    tensor_two_d,
    axis = None,
    keepdims=False,
    name = None
)


<tf.Tensor: shape=(), dtype=int32, numpy=35>

In [ ]:
tf.math.reduce_max(  # Gets the max value, similarly we have reduce_min
    tensor_two_d,
    axis = None,
    keepdims=False,
    name = None
)


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
# sigmoid(x) = y = 1/(1+exp(-x))

In [ ]:
# matmux is matrix multiplication

x_1 = tf.constant([[1, 2, 0],
                  [3, 5, -1]])

x_2 = tf.constant([[1, 2, 0],
                   [3, 5, -1],
                   [4, 5, 6]])

tf.linalg.matmul(x_1, x_2)

# we can have various more possibilities like transpose, adjoint, sparse

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [ ]:
tf.transpose(x_2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  3,  4],
       [ 2,  5,  5],
       [ 0, -1,  6]], dtype=int32)>

In [ ]:
tf.linalg.matmul( # Various properties we can pass
    x_1,
    x_2,
    transpose_a=False, # a is x_1
    transpose_b=False, # b is x_2
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [ ]:
x_3 = tf.constant([[1, 2, 0, 2],
                   [3, 5, -1, 2]])

x_1@x_2
# @: This symbol represents matrix multiplication in TensorFlow when used between tensors.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [ ]:

input = tf.constant([[ 0,  1,  2, 3],
               [-1,  0,  1, 2],
               [-2, -1,  0, 1],
               [-3, -2, -1, 0]])

# The indicator function
# in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper)
# m and n are indexes of the matrix

tf.linalg.band_part(input, 1, -1)
tf.linalg.band_part(input, 2, 1)

# Some special cases
#  tf.linalg.band_part(input, 0, -1) ==> Upper triangular matrix.
#  tf.linalg.band_part(input, -1, 0) ==> Lower triangular matrix.
#  tf.linalg.band_part(input, 0, 0) ==> Diagonal.

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  0,  0],
       [-1,  0,  1,  0],
       [-2, -1,  0,  1],
       [ 0, -2, -1,  0]], dtype=int32)>

In [ ]:
# tf.linalg.inv(
#     input, adjoint=False, name=None
# )

# Finding inverse for the matrix

In [ ]:
# einsum is used to simplify the matrix equation
# ij, jk -> ik


# Matrix Multiplication

m0 = tf.random.normal(shape=[2, 3])
m1 = tf.random.normal(shape=[3, 5])
e = tf.einsum('ij, jk -> ik', m0, m1)

print(e.shape)


(2, 5)


In [ ]:
# Dot Product
u = tf.random.normal(shape=[5])
v = tf.random.normal(shape=[5])

e = tf.einsum('i,i->', u, v)
print(e.shape)

()


In [ ]:
# Transpose
m = tf.ones(2,3)
e = tf.einsum('ij->ji', m0)
print(e.shape)

(3, 2)


In [ ]:
# Batch Matrix Multiplication
s = tf.random.normal(shape=[7,5,3])
t = tf.random.normal(shape=[7,3,2])
e = tf.einsum('bij,bjk->bik', s, t)

print(e.shape)

In [45]:
x = tf.constant([2, 3, 4, 5])
print(x.shape)
print("----------------")

y = tf.expand_dims(x, axis=0)
print(y)
print(y.shape)
# a negative axis counts from the end so axis=-1 adds an inner most dimension

# like expansion we can also squeeze [removes dimensions of size 1]

(4,)
----------------
tf.Tensor(
[[2]
 [3]
 [4]
 [5]], shape=(4, 1), dtype=int32)
(4, 1)


In [46]:
x_reshape = tf.constant([[2, 5, 6, 6],
                         [4, 6, 1, 2]])
# tf.reshape(x_reshape, [8])
tf.reshape(x_reshape, [4, 2])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 5],
       [6, 6],
       [4, 6],
       [1, 2]], dtype=int32)>

In [49]:
tf.reshape(x_reshape, [-1])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([2, 5, 6, 6, 4, 6, 1, 2], dtype=int32)>

In [52]:
t1 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t2 = tf.constant([[7, 8, 9],
                  [10, 11, 12]])

tf.concat([t1, t2], axis = 1)

# shape1 = (1, 2, 3)
# shape2 = (1, 2, 3)

# axis = 0
# new shape would be (2, 2, 3)

# axis = 1
# new shape would be (1, 4, 3)

# axis = 2
# new shape would be (1, 2, 6)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [53]:
tf.concat([t1, t2], axis = 0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [55]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])

tf.stack([x, y, z], axis = 0)

# if axis == 0 then the output tensor will have the shape (N, A, B, C). if axis == 1 then the output tensor will have the shape (A, N, B, C).

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [56]:
tf.stack([t1, t2], axis = 2)

# shape - 2 tensors are there t1 and t2
# so shape is -> 2 <-, 2, 3


# 4, 3 + 4, 3 -> 2, 4, 3 --- axis = 0
# 4, 3 + 4, 3 -> 4, 2, 3 --- axis = 1
# 4, 3 + 4, 3 -> 4, 3, 2 --- axis = 2

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

In [15]:
tf.stack([t1, t2], axis = 1)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]], dtype=int32)>

In [18]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1], [2, 2]])  # 1 row above and 1 row below, 2 columns left and 2 columns right

tf.pad(t, paddings)
# tf.pad(t, paddings, constant_values = 3)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [22]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params.shape)
params[1:3+1]

(6,)


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [60]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(params.shape)
tf.gather(params, [0, 2, 3], axis = 0) # In this we are saying that we want 0th, 2nd and 3rd index

(4, 3)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [20., 21., 22.],
       [30., 31., 32.]], dtype=float32)>

In [29]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(params.shape)
tf.gather(params, [0, 2], axis = 1)

(4, 3)


<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.,  2.],
       [10., 12.],
       [20., 22.],
       [30., 32.]], dtype=float32)>

In [5]:
# indices = [[0],
#            [1]]

indices = [1, 1]

params = [['a', 'b'],
          ['c', 'd']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(), dtype=string, numpy=b'd'>

In [6]:
indices = [ [0, 1],
            [1, 0]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)>

In [7]:
indices = [ [[0, 1],
            [1, 0]],

            [[0, 0],
            [1, 1]],

            ]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [8]:
indices = [ [0, 1],
            [1, 0]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices, batch_dims = 1) # Now batch is well aware that 1st block from a0 to d0 it belongs the [0, 1] and a1 to d1 it belongs to 1, 0
# so it starts from 0 matching a0 b0 then 1 which is b0
# similarly 1 0 -> c1 d1 then 0 which is c1

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b0', b'c1'], dtype=object)>