<a href="https://colab.research.google.com/github/ArjunMal1311/ML/blob/main/1-Tensorflow/2-Second_Hand_Car.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("train.csv")
df.head()

v.id  on road old  on road now  years      km  rating  condition  economy  \
0     1       535651       798186      3   78945       1          2       14   
1     2       591911       861056      6  117220       5          9        9   
2     3       686990       770762      2  132538       2          8       15   
3     4       573999       722381      4  101065       4          3       11   
4     5       691388       811335      6   61559       3          9       12   

   top speed  hp  torque  current price  
0        177  73     123       351318.0  
1        148  74      95       285001.5  
2        181  53      97       215386.0  
3        197  54     116       244295.5  
4        160  53     105       531114.5

In [4]:
df.columns

Index(['v.id', 'on road old', 'on road now', 'years', 'km', 'rating',
       'condition', 'economy', 'top speed', 'hp', 'torque', 'current price'],
      dtype='object')

In [5]:
# now we are taking years to torque as inputs so these are independent variables and output would
# be price so its depending on the above parameters
# [Ignoring id, road old, road now]

In [6]:
tensor_data = tf.constant(df)
tensor_data = tf.cast(tensor_data, tf.float32)

tensor_data

<tf.Tensor: shape=(1000, 12), dtype=float32, numpy=
array([[1.000000e+00, 5.356510e+05, 7.981860e+05, ..., 7.300000e+01,
        1.230000e+02, 3.513180e+05],
       [2.000000e+00, 5.919110e+05, 8.610560e+05, ..., 7.400000e+01,
        9.500000e+01, 2.850015e+05],
       [3.000000e+00, 6.869900e+05, 7.707620e+05, ..., 5.300000e+01,
        9.700000e+01, 2.153860e+05],
       ...,
       [9.980000e+02, 6.463440e+05, 8.427330e+05, ..., 1.130000e+02,
        8.900000e+01, 4.058710e+05],
       [9.990000e+02, 5.355590e+05, 7.324390e+05, ..., 1.120000e+02,
        1.280000e+02, 7.439800e+04],
       [1.000000e+03, 5.901050e+05, 7.797430e+05, ..., 9.900000e+01,
        9.600000e+01, 4.149385e+05]], dtype=float32)>

In [10]:
tensor_data = tf.random.shuffle(tensor_data)
tensor_data[:5]

<tf.Tensor: shape=(5, 12), dtype=float32, numpy=
array([[7.000000e+01, 6.859350e+05, 7.840380e+05, 5.000000e+00,
        1.114610e+05, 2.000000e+00, 8.000000e+00, 1.200000e+01,
        1.420000e+02, 7.300000e+01, 1.140000e+02, 3.042165e+05],
       [8.410000e+02, 5.653100e+05, 7.000180e+05, 7.000000e+00,
        1.300040e+05, 1.000000e+00, 8.000000e+00, 1.300000e+01,
        1.630000e+02, 5.200000e+01, 9.700000e+01, 1.208695e+05],
       [4.730000e+02, 5.083700e+05, 8.621880e+05, 6.000000e+00,
        5.788100e+04, 5.000000e+00, 1.000000e+01, 8.000000e+00,
        1.890000e+02, 9.900000e+01, 1.140000e+02, 5.016625e+05],
       [4.170000e+02, 6.354870e+05, 8.174840e+05, 5.000000e+00,
        7.680500e+04, 2.000000e+00, 1.000000e+00, 9.000000e+00,
        1.350000e+02, 1.040000e+02, 1.210000e+02, 4.179400e+05],
       [5.000000e+00, 6.913880e+05, 8.113350e+05, 6.000000e+00,
        6.155900e+04, 3.000000e+00, 9.000000e+00, 1.200000e+01,
        1.600000e+02, 5.300000e+01, 1.050000e+02, 5

In [12]:
X = tensor_data[:, 3:-1] # Ignoring first 3 columns and the price column

In [16]:
X.shape

TensorShape([1000, 8])

In [15]:
X[:5]

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[5.00000e+00, 1.11461e+05, 2.00000e+00, 8.00000e+00, 1.20000e+01,
        1.42000e+02, 7.30000e+01, 1.14000e+02],
       [7.00000e+00, 1.30004e+05, 1.00000e+00, 8.00000e+00, 1.30000e+01,
        1.63000e+02, 5.20000e+01, 9.70000e+01],
       [6.00000e+00, 5.78810e+04, 5.00000e+00, 1.00000e+01, 8.00000e+00,
        1.89000e+02, 9.90000e+01, 1.14000e+02],
       [5.00000e+00, 7.68050e+04, 2.00000e+00, 1.00000e+00, 9.00000e+00,
        1.35000e+02, 1.04000e+02, 1.21000e+02],
       [6.00000e+00, 6.15590e+04, 3.00000e+00, 9.00000e+00, 1.20000e+01,
        1.60000e+02, 5.30000e+01, 1.05000e+02]], dtype=float32)>

In [20]:
y = tensor_data[:, -1]
y.shape

TensorShape([1000])

In [21]:
# Adding extra dimension
y = tf.expand_dims(y, axis = -1)
y[:5]

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[304216.5],
       [120869.5],
       [501662.5],
       [417940. ],
       [531114.5]], dtype=float32)>

In [22]:
from tensorflow.keras.layers import Normalization

In [30]:
# normalizer = Normalization(mean = 5, variance = 4)
# x_normalized = tf.constant([[3, 4, 5, 6, 7]])    # ((x-mu)/sigma)
# normalizer(x_normalized)

normalizer = Normalization()
x_normalized = tf.constant([[3, 5, 5, 6, 7],
                            [4, 5, 6, 9, 8]]) # means and SD are gone column wise, mean -> (3+4)/2 --> 3.5 and SD would be 3.5-3 --> 0.5, so overall we get (x-mu)/SD so (4-3.5)/0.5 which is 1

normalizer.adapt(x_normalized)
normalizer(x_normalized)



<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-1.,  0., -1., -1., -1.],
       [ 1.,  0.,  1.,  1.,  1.]], dtype=float32)>

In [31]:
# We will normalize the 8 columns of X

normalizer = Normalization()
normalizer.adapt(X)
normalizer(X)[:5]

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[ 0.2554968 ,  0.3839451 , -0.7046623 ,  0.8529821 ,  0.16820414,
        -1.2912167 , -0.56303596,  0.5025149 ],
       [ 1.4194922 ,  1.0203769 , -1.4178834 ,  0.8529821 ,  0.6167485 ,
        -0.20193343, -1.5870925 , -0.3051557 ],
       [ 0.83749455, -1.4550246 ,  1.4350008 ,  1.561439  , -1.6259733 ,
         1.146703  ,  0.70484364,  0.5025149 ],
       [ 0.2554968 , -0.8055162 , -0.7046623 , -1.6266171 , -1.177429  ,
        -1.6543111 ,  0.94866663,  0.8350851 ],
       [ 0.83749455, -1.3287885 ,  0.00855871,  1.2072105 ,  0.16820414,
        -0.35754532, -1.5383279 ,  0.07492457]], dtype=float32)>